application:
  name: "purchase-order"

server:
  port: 8084

okDesk:
  uri: "http://localhost:8084"
  getIssuesSinceDaysAgo: 30
  comment_marker: "Add record in google sheet"
  okDeskAuthorId: 4654
  api_token: "123"

spreadsheet:
  #файл с сертификатом от гугул
  credential_file_name: "credentials.json"
  token_directory: "tokens"
  #тестовая таблица
  id: "15xEoH4Gs-mQpfV4A5fJ7Pif0VaFEjZirYBY-Cd69_dA"
  order_id_column_title: "Получение заявки на услугу в Ariba"
  template_sheet_title: "Шаблон для создания других страниц"

spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:fakeOkDeskServer
    driverClassName: org.h2.Driver
    username: sa
    password: 123
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect